"""Add agent swarm system tables

Revision ID: f7a8e9d3b4c1
Revises: 59f76edd7bbe
Create Date: 2026-03-31 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f7a8e9d3b4c1"
down_revision: Union[str, None] = "59f76edd7bbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create swarm_agents table
    op.create_table(
        "swarm_agents",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_type", sa.String(50), nullable=False),
        sa.Column("agent_class", sa.String(50), nullable=False),
        sa.Column("capabilities", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("status", sa.String(20), nullable=True, server_default="idle"),
        sa.Column("config", postgresql.JSONB(), nullable=True, server_default="{}"),
        sa.Column("last_active_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_agents_agent_type", "swarm_agents", ["agent_type"])

    # Create swarm_agent_metrics table
    op.create_table(
        "swarm_agent_metrics",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("tasks_completed", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("tasks_failed", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("avg_confidence", sa.Float(), nullable=True),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("avg_execution_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "last_calculated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["agent_id"], ["swarm_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_id"),
    )

    # Create swarm_executions table
    op.create_table(
        "swarm_executions",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_type", sa.String(100), nullable=False),
        sa.Column("task_description", sa.Text(), nullable=True),
        sa.Column(
            "required_capabilities",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column("optimal_swarm_size", sa.Integer(), nullable=True, server_default="3"),
        sa.Column("input_payload", postgresql.JSONB(), nullable=True),
        sa.Column("output_payload", postgresql.JSONB(), nullable=True),
        sa.Column("status", sa.String(20), nullable=True, server_default="pending"),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("success", sa.String(10), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("feedback_score", sa.Integer(), nullable=True),
        sa.Column("context_location", sa.String(255), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_executions_organization_id", "swarm_executions", ["organization_id"])
    op.create_index("ix_swarm_executions_task_type", "swarm_executions", ["task_type"])
    op.create_index("ix_swarm_executions_status", "swarm_executions", ["status"])

    # Create swarm_execution_agents table (many-to-many)
    op.create_table(
        "swarm_execution_agents",
        sa.Column("execution_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("agent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("execution_order", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("contributed_to_success", sa.String(10), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["swarm_executions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["agent_id"], ["swarm_agents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("execution_id", "agent_id"),
    )

    # Create swarm_pheromones table
    op.create_table(
        "swarm_pheromones",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("location", sa.String(255), nullable=False),
        sa.Column("data_type", sa.String(100), nullable=False),
        sa.Column("strength", sa.Float(), nullable=False, server_default="1.0"),
        sa.Column("hint", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(), nullable=True, server_default="{}"),
        sa.Column("created_by_agent", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_strengthened_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["created_by_agent"], ["swarm_agents.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_pheromones_location", "swarm_pheromones", ["location"])
    op.create_index("ix_swarm_pheromones_organization_id", "swarm_pheromones", ["organization_id"])

    # Create swarm_conflicts table
    op.create_table(
        "swarm_conflicts",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("execution_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("conflict_type", sa.String(100), nullable=True),
        sa.Column("proposals", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("resolution", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("resolution_reason", sa.Text(), nullable=True),
        sa.Column("resolution_strategy", sa.String(50), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["swarm_executions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_conflicts_execution_id", "swarm_conflicts", ["execution_id"])

    # Create swarm_learnings table
    op.create_table(
        "swarm_learnings",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("learning_type", sa.String(50), nullable=True),
        sa.Column("context", sa.String(255), nullable=True),
        sa.Column("insight", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True, server_default="0.5"),
        sa.Column("source_execution_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "applicable_agent_types",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column("times_applied", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("success_rate", sa.Float(), nullable=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("last_applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_execution_id"], ["swarm_executions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_learnings_organization_id", "swarm_learnings", ["organization_id"])
    op.create_index("ix_swarm_learnings_learning_type", "swarm_learnings", ["learning_type"])

    # Create swarm_task_queue table
    op.create_table(
        "swarm_task_queue",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("task_type", sa.String(100), nullable=False),
        sa.Column("task_description", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True, server_default="5"),
        sa.Column(
            "required_capabilities",
            postgresql.ARRAY(sa.String()),
            nullable=True,
            server_default="{}",
        ),
        sa.Column("optimal_swarm_size", sa.Integer(), nullable=True, server_default="3"),
        sa.Column("input_payload", postgresql.JSONB(), nullable=True),
        sa.Column("context_location", sa.String(255), nullable=True),
        sa.Column("status", sa.String(20), nullable=True, server_default="queued"),
        sa.Column(
            "queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("execution_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["execution_id"], ["swarm_executions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_swarm_task_queue_organization_id", "swarm_task_queue", ["organization_id"])
    op.create_index("ix_swarm_task_queue_status", "swarm_task_queue", ["status"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_swarm_task_queue_status", table_name="swarm_task_queue")
    op.drop_index("ix_swarm_task_queue_organization_id", table_name="swarm_task_queue")
    op.drop_table("swarm_task_queue")

    op.drop_index("ix_swarm_learnings_learning_type", table_name="swarm_learnings")
    op.drop_index("ix_swarm_learnings_organization_id", table_name="swarm_learnings")
    op.drop_table("swarm_learnings")

    op.drop_index("ix_swarm_conflicts_execution_id", table_name="swarm_conflicts")
    op.drop_table("swarm_conflicts")

    op.drop_index("ix_swarm_pheromones_organization_id", table_name="swarm_pheromones")
    op.drop_index("ix_swarm_pheromones_location", table_name="swarm_pheromones")
    op.drop_table("swarm_pheromones")

    op.drop_table("swarm_execution_agents")

    op.drop_index("ix_swarm_executions_status", table_name="swarm_executions")
    op.drop_index("ix_swarm_executions_task_type", table_name="swarm_executions")
    op.drop_index("ix_swarm_executions_organization_id", table_name="swarm_executions")
    op.drop_table("swarm_executions")

    op.drop_table("swarm_agent_metrics")

    op.drop_index("ix_swarm_agents_agent_type", table_name="swarm_agents")
    op.drop_table("swarm_agents")
    # ### end Alembic commands ###
